import{S as M,N as $,P as S,i as w,a as A}from"./assets/vendor-BYj0TJZP.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))r(n);new MutationObserver(n=>{for(const i of n)if(i.type==="childList")for(const a of i.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function s(n){const i={};return n.integrity&&(i.integrity=n.integrity),n.referrerPolicy&&(i.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?i.credentials="include":n.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(n){if(n.ep)return;n.ep=!0;const i=s(n);fetch(n.href,i)}})();new M(".swiper-feedbacks",{modules:[$,S],slidesPerView:1,spaceBetween:24,loop:!1,pagination:{el:".swiper-pagination-feedbacks",clickable:!0},navigation:{nextEl:".swiper-button-next-feedbacks",prevEl:".swiper-button-prev-feedbacks"}});const y="https://books-backend.p.goit.global",O="/books/category-list",x="/books/top-books",P="/books/category",D="/books/",_=10,I=24,o={categoryToggleBtn:document.querySelector("[data-category-list-toggle]"),categoryMenuContainer:document.querySelector("[data-category-list]"),categoryListElement:document.querySelector(".books-categories-list"),booksContainer:document.querySelector(".js-books-list"),showMoreBtn:document.querySelector(".books-show-more-btn"),booksShowingCount:document.querySelector(".books-showing-count")};let d=[],l="All categories",c=[],m=0,g=0;function k(){return window.innerWidth<768?_:I}async function b(e,t={}){try{const{data:s}=await A(e,t);return s}catch(s){throw w.error({title:"Error",titleColor:"#ffffff",message:`Request failed: <u>${s.message}</u>`,messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight",timeout:4e3,animateInside:!0,progressBar:!1,close:!1,closeOnClick:!0}),s}}async function H(){return(await b(`${y}${O}`)).map(t=>t.list_name)}async function q(){return(await b(`${y}${x}`)).flatMap(t=>t.books)}async function R(e){const t={category:e};return await b(`${y}${P}`,{params:t})}async function Y(e){const t=await b(`${y}${D}${e}`);return console.log(`Book details for ID ${e}:`,t),t}function N(e){const t=`
    <li class="books-categories-item">
      <a href="#" class="books-categories-list-link ${l==="All categories"?"active":""}">All categories</a>
    </li>
  `,s=e.filter(r=>r!=="All categories").map(r=>`
        <li class="books-categories-item">
          <a href="#" class="books-categories-list-link ${r===l?"active":""}">${r}</a>
        </li>
      `).join("");return t+s}function K(e){return e.length===0?'<li class="no-books-message">No books found for this category.</li>':e.map(({book_image:t,title:s,author:r,price:n,_id:i})=>`
        <li class="books-card" data-book-id="${i}">
            <img class="books-card-img" src="${t}" alt="${s}"/>
            <div class="books-info">
                <div class="books-info-left">
                   <h4 class="books-h section-subtitle">${s}</h4>
                   <p class="books-text">${r}</p>
                   
                </div>
                <p class="books-price-text">$${n}</p>
            </div>
            <button class="learn-more-btn" type="button" data-book-modal-open data-book-id="${i}">Learn more</button>
        </li>
    `).join("")}function C(){o.categoryListElement.innerHTML=N(d),o.categoryListElement.querySelectorAll(".books-categories-list-link").forEach(e=>{e.addEventListener("click",z)})}async function B(){o.booksContainer.innerHTML="",o.showMoreBtn.classList.add("show-more-hidden"),l==="All categories"?c=await q():c=await R(l),m=0,g=0,h()}function h(e=k()){const t=m*e,s=Math.min(t+e,c.length),r=c.slice(t,s);o.booksContainer.insertAdjacentHTML("beforeend",K(r)),g=s,o.booksShowingCount.textContent=`Showing ${g} of ${c.length}`,m++,g<c.length?o.showMoreBtn.classList.remove("show-more-hidden"):o.showMoreBtn.classList.add("show-more-hidden")}function j(){const e=o.categoryMenuContainer.classList.toggle("is-open");o.categoryToggleBtn.classList.toggle("is-open"),e&&f()}async function z(e){e.preventDefault();const t=e.target.textContent;if(l===t){o.categoryMenuContainer.classList.remove("is-open"),o.categoryToggleBtn.classList.remove("is-open");return}l=t,C(),await B(),o.categoryMenuContainer.classList.remove("is-open"),o.categoryToggleBtn.classList.remove("is-open")}async function F(e){const t=e.target.closest(".learn-more-btn");if(t){const s=t.dataset.bookId;if(s)try{const r=await Y(s);alert(`Book Title: ${r.title}
Author: ${r.author}
Description: ${r.description.substring(0,100)}...`)}catch(r){alert("Failed to load book details. Please try again later."),console.error("Failed to show book details:",r)}}}async function G(){o.showMoreBtn.disabled=!0;try{h(4)}catch(e){w.error({title:"Error",message:`Failed to load books: ${e.message}`,backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff",position:"topRight"})}finally{o.showMoreBtn.disabled=!1}}async function U(){d=await H(),d.includes("All categories")||(d=["All categories",...d]),C(),o.categoryToggleBtn.firstChild.textContent="Categories ",await B();let e=k();window.addEventListener("resize",()=>{const t=k();t!==e&&(e=t,o.booksContainer.innerHTML="",m=0,g=0,h(t))})}const u=o.categoryListElement,p=document.querySelector(".books-categories-scrollbar-thumb");function f(){const{scrollTop:e,scrollHeight:t,clientHeight:s}=u,r=s/t,n=Math.max(r*s,24),i=s-n,a=e/(t-s)*i||0;p.style.height=n+"px",p.style.top=a+"px"}u.addEventListener("scroll",f);window.addEventListener("resize",f);f();let L=!1,v=0,T=0;p.addEventListener("mousedown",e=>{L=!0,v=e.clientY,T=u.scrollTop,document.body.style.userSelect="none"});document.addEventListener("mousemove",e=>{if(!L)return;const{scrollHeight:t,clientHeight:s}=u,r=t-s,n=p.offsetHeight,i=s-n,E=(e.clientY-v)/i*r;u.scrollTop=T+E,f()});document.addEventListener("mouseup",()=>{L=!1,document.body.style.userSelect=""});o.categoryToggleBtn.addEventListener("click",j);o.booksContainer.addEventListener("click",e=>{const t=e.target.closest(".learn-more-btn");t&&(t.blur(),F(e))});o.showMoreBtn.addEventListener("click",G);window.addEventListener("click",function(e){!o.categoryToggleBtn.contains(e.target)&&!o.categoryMenuContainer.contains(e.target)&&(o.categoryMenuContainer.classList.remove("is-open"),o.categoryToggleBtn.classList.remove("is-open"))});document.addEventListener("DOMContentLoaded",U);
//# sourceMappingURL=index.js.map
