import{S as M,N as S,P as $,i as L,a as A}from"./assets/vendor-DQb83OiD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const i of document.querySelectorAll('link[rel="modulepreload"]'))n(i);new MutationObserver(i=>{for(const s of i)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(i){const s={};return i.integrity&&(s.integrity=i.integrity),i.referrerPolicy&&(s.referrerPolicy=i.referrerPolicy),i.crossOrigin==="use-credentials"?s.credentials="include":i.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(i){if(i.ep)return;i.ep=!0;const s=o(i);fetch(i.href,s)}})();document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".events-swiper");e&&new M(e,{modules:[S,$],slidesPerView:1,spaceBetween:24,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:3}},pagination:{el:".ev-pagination",clickable:!0,renderBullet:(t,o)=>`<li class="${o}" aria-label="Go to slide ${t+1}"></li>`,bulletClass:"ev-dot",bulletActiveClass:"ev-dot--active"},navigation:{nextEl:".events-swiper-btn-next",prevEl:".events-swiper-btn-prev"},watchOverflow:!0})});const m="https://books-backend.p.goit.global",O="/books/category-list",P="/books/top-books",D="/books/category",x="/books/",q=10,I=24,r={categoryToggleBtn:document.querySelector("[data-category-list-toggle]"),categoryMenuContainer:document.querySelector("[data-category-list]"),categoryListElement:document.querySelector(".books-categories-list"),booksContainer:document.querySelector(".js-books-list"),showMoreBtn:document.querySelector(".books-show-more-btn"),booksShowingCount:document.querySelector(".books-showing-count")};let d=[],c="All categories",l=[],b=0,u=0;function k(){return window.innerWidth<768?q:I}async function p(e,t={}){try{const{data:o}=await A(e,t);return o}catch(o){throw L.error({title:"Error",titleColor:"#ffffff",message:`Request failed: <u>${o.message}</u>`,messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight",timeout:4e3,animateInside:!0,progressBar:!1,close:!1,closeOnClick:!0}),o}}async function _(){return(await p(`${m}${O}`)).map(t=>t.list_name)}async function H(){return(await p(`${m}${P}`)).flatMap(t=>t.books)}async function R(e){const t={category:e};return await p(`${m}${D}`,{params:t})}async function N(e){const t=await p(`${m}${x}${e}`);return console.log(`Book details for ID ${e}:`,t),t}function Y(e){const t=`
    <li class="books-categories-item">
      <a href="#" class="books-categories-list-link ${c==="All categories"?"active":""}">All categories</a>
    </li>
  `,o=e.filter(n=>n!=="All categories").map(n=>`
        <li class="books-categories-item">
          <a href="#" class="books-categories-list-link ${n===c?"active":""}">${n}</a>
        </li>
      `).join("");return t+o}function V(e){return e.length===0?'<li class="no-books-message">No books found for this category.</li>':e.map(({book_image:t,title:o,author:n,price:i,_id:s})=>`
        <li class="books-card" data-book-id="${s}">
            <img class="books-card-img" src="${t}" alt="${o}"/>
            <div class="books-info">
                <div class="books-info-left">
                   <h4 class="books-h section-subtitle">${o}</h4>
                   <p class="books-text">${n}</p>
                   
                </div>
                <p class="books-price-text">$${i}</p>
            </div>
            <button class="learn-more-btn" type="button" data-book-modal-open data-book-id="${s}">Learn more</button>
        </li>
    `).join("")}function v(){r.categoryListElement.innerHTML=Y(d),r.categoryListElement.querySelectorAll(".books-categories-list-link").forEach(e=>{e.addEventListener("click",G)})}async function C(){r.booksContainer.innerHTML="",r.showMoreBtn.classList.add("show-more-hidden"),c==="All categories"?l=await H():l=await R(c),b=0,u=0,h()}function h(e=k()){const t=b*e,o=Math.min(t+e,l.length),n=l.slice(t,o);r.booksContainer.insertAdjacentHTML("beforeend",V(n)),u=o,r.booksShowingCount.textContent=`Showing ${u} of ${l.length}`,b++,u<l.length?r.showMoreBtn.classList.remove("show-more-hidden"):r.showMoreBtn.classList.add("show-more-hidden")}function K(){const e=r.categoryMenuContainer.classList.toggle("is-open");r.categoryToggleBtn.classList.toggle("is-open"),e&&f()}async function G(e){e.preventDefault();const t=e.target.textContent;if(c===t){r.categoryMenuContainer.classList.remove("is-open"),r.categoryToggleBtn.classList.remove("is-open");return}c=t,v(),await C(),r.categoryMenuContainer.classList.remove("is-open"),r.categoryToggleBtn.classList.remove("is-open")}async function j(e){const t=e.target.closest(".learn-more-btn");if(t){const o=t.dataset.bookId;if(o)try{const n=await N(o);alert(`Book Title: ${n.title}
Author: ${n.author}
Description: ${n.description.substring(0,100)}...`)}catch(n){alert("Failed to load book details. Please try again later."),console.error("Failed to show book details:",n)}}}async function z(){r.showMoreBtn.disabled=!0;try{h(4)}catch(e){L.error({title:"Error",message:`Failed to load books: ${e.message}`,backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff",position:"topRight"})}finally{r.showMoreBtn.disabled=!1}}async function F(){d=await _(),d.includes("All categories")||(d=["All categories",...d]),v(),r.categoryToggleBtn.firstChild.textContent="Categories ",await C();let e=k();window.addEventListener("resize",()=>{const t=k();t!==e&&(e=t,r.booksContainer.innerHTML="",b=0,u=0,h(t))})}const g=r.categoryListElement,y=document.querySelector(".books-categories-scrollbar-thumb");function f(){const{scrollTop:e,scrollHeight:t,clientHeight:o}=g,n=o/t,i=Math.max(n*o,24),s=o-i,a=e/(t-o)*s||0;y.style.height=i+"px",y.style.top=a+"px"}g.addEventListener("scroll",f);window.addEventListener("resize",f);f();let w=!1,E=0,B=0;y.addEventListener("mousedown",e=>{w=!0,E=e.clientY,B=g.scrollTop,document.body.style.userSelect="none"});document.addEventListener("mousemove",e=>{if(!w)return;const{scrollHeight:t,clientHeight:o}=g,n=t-o,i=y.offsetHeight,s=o-i,T=(e.clientY-E)/s*n;g.scrollTop=B+T,f()});document.addEventListener("mouseup",()=>{w=!1,document.body.style.userSelect=""});r.categoryToggleBtn.addEventListener("click",K);r.booksContainer.addEventListener("click",e=>{const t=e.target.closest(".learn-more-btn");t&&(t.blur(),j(e))});r.showMoreBtn.addEventListener("click",z);window.addEventListener("click",function(e){!r.categoryToggleBtn.contains(e.target)&&!r.categoryMenuContainer.contains(e.target)&&(r.categoryMenuContainer.classList.remove("is-open"),r.categoryToggleBtn.classList.remove("is-open"))});document.addEventListener("DOMContentLoaded",F);document.addEventListener("DOMContentLoaded",()=>{const e=new Swiper("#feedbacks-slider",{slidesPerView:1,spaceBetween:24,grabCursor:!0,keyboard:{enabled:!0,onlyInViewport:!0},a11y:{enabled:!0},watchOverflow:!0,navigation:{nextEl:".btn-next",prevEl:".btn-prev",disabledClass:"is-disabled",lockClass:"is-locked"},pagination:{el:".slider-dots",clickable:!0,bulletClass:"dot",bulletActiveClass:"dot--active"},breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:3}}}),t=document.querySelector(".btn-prev"),o=document.querySelector(".btn-next");function n(){if(t){const s=t.classList.contains("is-disabled");t.toggleAttribute("disabled",s),t.setAttribute("aria-disabled",String(s))}if(o){const s=o.classList.contains("is-disabled");o.toggleAttribute("disabled",s),o.setAttribute("aria-disabled",String(s))}}e.on("init",n),e.on("slideChange",n),e.on("reachBeginning",n),e.on("reachEnd",n),e.on("fromEdge",n),n();function i(s){s.key==="ArrowLeft"&&(s.preventDefault(),t==null||t.click()),s.key==="ArrowRight"&&(s.preventDefault(),o==null||o.click())}t==null||t.addEventListener("keydown",i),o==null||o.addEventListener("keydown",i)});
//# sourceMappingURL=index.js.map
